### ISSUE TITLE
Too Many Request

### ISSUE THREAD

**Issue by edwolfe3** [openhab/openhab-alexa#347]
I'm trying to get echo to play a tunein station.  I'm using a "test" rule that plays the station when I say "nine".  When the rule runs, i get the following output:

```
2020-01-04 18:16:07.242 [vent.ItemStateChangedEvent] - Echo_Office_LastVoiceCommand changed from nine to 

2020-01-04 18:16:07.246 [vent.ItemStateChangedEvent] - Echo_Office_LastVoiceCommand changed from  to nine

2020-01-04 18:16:08.048 [ome.event.ItemCommandEvent] - Item 'Echo_Office_TTS' received command TEN

2020-01-04 18:16:08.063 [nt.ItemStatePredictedEvent] - Echo_Office_TTS predicted to become TEN

2020-01-04 18:16:08.072 [ome.event.ItemCommandEvent] - Item 'Echo_Office_MusicProviderId' received command TUNEIN

2020-01-04 18:16:08.092 [ome.event.ItemCommandEvent] - Item 'Echo_Office_PlayMusicCommand' received command s306312

2020-01-04 18:16:08.104 [ome.event.ItemCommandEvent] - Item 'Echo_Office_Volume' received command 80

2020-01-04 18:16:08.117 [vent.ItemStateChangedEvent] - Echo_Office_TTS changed from  to TEN

2020-01-04 18:16:08.118 [nt.ItemStatePredictedEvent] - Echo_Office_MusicProviderId predicted to become TUNEIN

2020-01-04 18:16:08.127 [nt.ItemStatePredictedEvent] - Echo_Office_PlayMusicCommand predicted to become s306312

2020-01-04 18:16:08.136 [nt.ItemStatePredictedEvent] - Echo_Office_Volume predicted to become 80

2020-01-04 18:16:08.145 [vent.ItemStateChangedEvent] - Echo_Office_PlayMusicCommand changed from Sailing to s306312

2020-01-04 18:16:08.536 [vent.ItemStateChangedEvent] - Echo_Office_TTS changed from TEN to 

2020-01-04 18:16:08.541 [vent.ItemStateChangedEvent] - Echo_Office_PlayMusicCommand changed from s306312 to 

==> /var/log/openhab2/openhab.log <==

2020-01-04 18:16:08.982 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.amazonechocontrol.internal.handler.EchoHandler@166c600': POST url 'https://alexa.amazon.com/api/behaviors/preview' failed: Too Many Requests

org.openhab.binding.amazonechocontrol.internal.HttpException: POST url 'https://alexa.amazon.com/api/behaviors/preview' failed: Too Many Requests

	at org.openhab.binding.amazonechocontrol.internal.Connection.makeRequest(Connection.java:654) ~[?:?]

	at org.openhab.binding.amazonechocontrol.internal.Connection.playMusicVoiceCommand(Connection.java:1734) ~[?:?]

	at org.openhab.binding.amazonechocontrol.internal.handler.EchoHandler.handleCommand(EchoHandler.java:439) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]

	at com.sun.proxy.$Proxy1211.handleCommand(Unknown Source) [?:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```
However, if I play the same station using my voice (it has the name Sailing), I get the following:

```
2020-01-04 18:28:15.428 [vent.ItemStateChangedEvent] - Echo_Office_LastVoiceCommand changed from nine to alexa

2020-01-04 18:28:19.469 [vent.ItemStateChangedEvent] - Echo_Office_LastVoiceCommand changed from alexa to play sailing from tunein radio

2020-01-04 18:28:22.167 [vent.ItemStateChangedEvent] - Echo_Office_RadioStationId changed from  to s306312

2020-01-04 18:28:22.172 [vent.ItemStateChangedEvent] - Echo_Office_Radio changed from OFF to ON

2020-01-04 18:28:22.175 [vent.ItemStateChangedEvent] - Echo_Office_Player changed from PAUSE to PLAY
```
My rule looks like this:

```
rule "test"
when
    Item Echo_Office_LastVoiceCommand changed to "nine"
then
    Echo_Office_TTS.sendCommand("TEN")
    Echo_Office_MusicProviderId.sendCommand("TUNEIN")
    Echo_Office_PlayMusicCommand.sendCommand("s306312")
    Echo_Office_Volume.sendCommand("80")
End
```

What am I doing wrong?

**Comment by jsetton** [comment]
Unless I am missing something, you are referring to an issue with the [Amazon Echo Control](https://www.openhab.org/addons/bindings/amazonechocontrol/) binding. This repository is for the [Alexa Smart Home Skill](https://www.openhab.org/docs/ecosystem/alexa/) allowing the control of  openHAB devices using Alexa voice commands.

You should post your issue on the [community forum](https://community.openhab.org/).
